#!/bin/bash

# Start the backend
echo "Starting the backend..."
cd backend
uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4 &
BACKEND_PID=$!

# Start the frontend
echo "Starting the frontend..."
cd ../frontend/url2pdf
npm run dev &
FRONTEND_PID=$!

# Wait for both processes to finish
wait $BACKEND_PID $FRONTEND_PID
